export const ActionTypes = {
    FETCHING_MOVIES_DATA: "FETCHING_MOVIES_DATA",
    FETCH_MOVIES_DATA: "FETCH_MOVIES_DATA",
    REMOVE_MOVIES_DATA: "REMOVE_MOVIES_DATA",
    GET_SEARCH_TERM: "GET_SEARCH_TERM",
    FETCHING_NOW_PLAYING: "FETCHING_NOW_PLAYING",
    FETCH_NOW_PLAYING: "FETCH_NOW_PLAYING",
    REMOVE_NOW_PLAYING: "REMOVE_NOW_PLAYING",
    FETCHING_COMING_SOON: "FETCHING_COMING_SOON",
    FETCH_COMING_SOON: "FETCH_COMING_SOON",
    REMOVE_COMING_SOON: "REMOVE_COMING_SOON",
}