export const ActionTypes = {
    FETCHING_MOVIES_DATA: "FETCHING_MOVIES_DATA",
    FETCH_MOVIES_DATA: "FETCH_MOVIES_DATA",
    REMOVE_MOVIES_DATA: "REMOVE_MOVIES_DATA",
    GET_SEARCH_TERM: "GET_SEARCH_TERM",
}